### PR TITLE
Fix search if external root dir starts with a dot

### LINKED ISSUE #740: [BUG] cannot search in root folder
**Describe the bug**
I have two folders in my password store root, the search won't work when I'm at root, only works if I go into one of them. 

**To Reproduce**
1. Go to home page
2. Click on search
3. type anything

**Expected behavior**
display search results from both folders

**Screenshots**
image
image
image

**Device information (please complete the following information):**
 - Device: Google Pixel 3
 - OS: stock ROM Android version 10.0
 - App version: 1.7.1

**Additional context**
The Recursive filtering is checked in Settings.

### PR DESCRIPTION
**Pull request by Hazegard**
## :loudspeaker: Type of change
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring

## :scroll: Description
This PR aims to not filter out the root folder.

## :bulb: Motivation and Context
This PR fixes a small bug I encountered.
My repository is located at /storage/emulated/0/.password-store.

However, in the autofill popup, since that my root folder is hidden, it is filtered out.
So the autofill menu was empty.

Edit: Fixes #740.

## :green_heart: How did you test it?
I checked that the autofill menu now shows entries

## :pencil: Checklist

- [ ] I ran `./gradlew spotlessApply` before submitting the PR
- [x] I reviewed submitted code

### CODE REVIEW

File: app/src/main/java/com/zeapo/pwdstore/SearchableRepositoryViewModel.kt [hunk 1]
```diff
@@ -266,7 +266,7 @@ class SearchableRepositoryViewModel(application: Application) : AndroidViewModel
 
     private fun listFilesRecursively(dir: File): Flow<File> {
         return dir
-            .walkTopDown().onEnter { file -> shouldTake(file) }
+            .walkTopDown().onEnter { file -> if (file == dir) true else shouldTake(file) }
```
Comment (FabianHenneke) [inline app/src/main/java/com/zeapo/pwdstore/SearchableRepositoryViewModel.kt:269]:
```suggestion
            // Take top directory even if it is hidden.
            .walkTopDown().onEnter { file -> file == dir || shouldTake(file) }
```

Comment (FabianHenneke) [reply app/src/main/java/com/zeapo/pwdstore/SearchableRepositoryViewModel.kt:269]: @Hazegard I find it a bit clearer this way, what do you think?

Comment (Hazegard) [reply app/src/main/java/com/zeapo/pwdstore/SearchableRepositoryViewModel.kt]: Thank you for your suggestion, I agree it's better!
