### PR TITLE
PasswordStore: refresh password list on swipe down in non-git mode

### LINKED ISSUE #845: [BUG] No-git store flow is broken
**Describe the bug**
In the legacy version of password store it was possible to setup the app so that it could use a password store that was not a Git repo. For example I use SyncThing to sync my password store across all my devices, and I could point the legacy app to that and tell it to not use Git.

**To Reproduce**
1. Store passwords to the android device somewhere on the device (e.g. /storage/emulated/0/Password Store)
2. Install Password Store 1.8.1
3. Go to Settings -> Repository
4. Enable External repository and select the directory the passwords are stored under "Select external repository".
5. Go back to the main screen and select "Refresh list"
6. Get asked to setup a git repo where it can clone passwords from

**Expected behavior**
For pass to use the selected directory and read the already stored password list without the need of a Git repo like how it worked with version 1.3.3

**Device information (please complete the following information):**
 - Device: Google Pixel 3XL
 - OS: vanilla Android 10
 - App version 1.8.1

### PR DESCRIPTION
**Pull request by msfjarvis**
## :loudspeaker: Type of change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## :scroll: Description
Refreshes the password list when swipe refresh is triggered and our repository does not have a `.git` directory.

## :bulb: Motivation and Context
Currently if there is no `.git` directory in the store, the swipe refresher will simply start the refresh animation
and stay stuck doing it, which is not good UX and also wasteful.

## :green_heart: How did you test it?
Create a non-git repository, pull down on password list and see it refresh and stop the animation.

## :pencil: Checklist

- [x] I formatted the code with the IDE's reformat action (Ctrl + Shift + L/Cmd + Shift + L)
- [x] I reviewed submitted code
- [ ] I added a [CHANGELOG](CHANGELOG.md) entry if applicable

## :crystal_ball: Next steps
Still need to reproduce and solve #845

### CODE REVIEW

File: app/src/main/java/com/zeapo/pwdstore/PasswordFragment.kt [hunk 1]
```diff
@@ -85,6 +85,11 @@ class PasswordFragment : Fragment(R.layout.password_recycler_view) {
                     startActivityForResult(intent, operationId)
                 }
             }
+        } else {
```
Comment (FabianHenneke) [inline app/src/main/java/com/zeapo/pwdstore/PasswordFragment.kt:88]: I don't know about all the workflows that allow to switch between a Git and a non-Git repository, but perhaps it would be safer to move the `if` into the `OnRefreshListener`?

**Comment by FabianHenneke** [comment]
I also edited your PR description to remove a "closing term" from the `Next steps` section which would have closed #845.
