### PR TITLE
Better detect uninitialized repositories and offer to clone

### LINKED ISSUE #61: Initial Repository Clone
I had to include the username in the entry field dedicated to the server such as this:

Username@bitbucket.org

to get a working url usable by jgit to get the initial repository clone done.

### LINKED ISSUE #357: jgit error: Attempt to read from field 'int org.eclipse.jgit.lib.AnyObjectId.w1' on a null object reference
I was so happy to see an android app I can use with my pass git repo :)

Ran into this jgit problem though...

I did the following:
* select the _local (hidden)_ option
* generate ssh key using the app
* put public key on my server
* add ssh details to my git repo (personal VPS server, with a bare git repo in `/git/pass.git`)
* attempt to pull from remote

Then comes the jgit error:

I wondered if my git repo was corrupt, but a `git fsck` finds no issues. I can clone the repo locally using the copy-n-pasted _Resulting URL_ box.

I am using version 1.2.0.73 from the play store which is the same version as the f-droid one.

### LINKED ISSUE #427: jgit null-object-reference error occurs when attempting to access Git repo by SSH
Steps to reproduce:
1. Import SSH key
2. Configure git repo settings, using SSH for auth
3. Choose "Pull from Remote"
4. Enter SSH key passphrase if any
5. See the following message: 
> An error occurred during a Git operation
> Error occurred during the pull operation, Message from jgit: Attempt to read from field 'int org.eclipse.jgit.lib.AnyObjectId.w1' on a null object reference 
> Caused by:
> null
> Please check the FAQ for possible reasons why this error might occur.

"Synchronize repository" throws the same error. 

* Moto E4 running Android 7.1.1
* Password Store app v1.2.0.75
* Bitbucket git repo which I use with `pass` on my computers

### LINKED ISSUE #490: Can't clone github repo
Protocol: ssh://
Username:   git
Server URL: github.com
Repo path:   bit9tream/.password-store.git
Aunthentication Mode: ssh-key

Resulting url: git@github.com:bit9tream/.password-store.git

Error occured during the sync operation. Message from jgit: Attempt to read from field 'int org.eclipse.jgit.lib.AnyObjectld.w1' on a null object reference 
Caused by: null

### LINKED ISSUE #736: [BUG] Error when adding local repository to the external MicroSD card.
**Describe the bug**
I have 'Password store' + 'OpenKeychain' and the pass repository on Gitlab.com. 
When I check in Settings an external repository (My Micro SD card) And try to synchronize the repository I see an error. I tried the authentication method via HTTPS and SSH, and both give an error. I noticed that in Totalcmd (for Android) the path to my External storage is /storage/0123-4567/* and in the settings of 'Password store' I see the path /storage/emulatet/0/* And it is not my External storage. When I don't check the internal storage path authentication goes well with HTTPS and with SSH.

**To Reproduce**
1. Open 'Password store'
2. Go to 'Settings'
3. Scroll down to 'External repository' and check it
4. Synchronize the repository
5. See error:
An error occurred while performing the operation Git
Error occurred during the sync
operation,
Please check the FAQ for possible
reasons why this error might
occur.Message from jgit:
Attempt to read from field ‘int
org.eclipse.jgit.lib.AnyObjectld.w1' on
a null object reference
Caused by:
null 

**Expected behavior**
I expect a successful synchronization with my repository server on Gitlab. 

**Screenshots**
https://i.imgur.com/TpS9ObW.png

**Device information (please complete the following information):**
 - Device: Lenovo Vibe P1a42
 - Device CPU: CPU: Qualcomm Snapdragon 615 (8 cores x 1.5GGHz)
 - Device RAM: 3Gb
 - Device internal storage: 16Gb (1.7Gb Aviabile)
 - Device external storage MicroSD: 57.95Gb (42.7Gb Aviabile)
 - OS: Android 6.0.1 
 - App version: 1.7.0

**Additional context**
Maybe the problem is that 'Password store' don't make the path to my external storage correctly. When I don't check the internal storage path authentication goes well with HTTPS and with SSH.

### PR DESCRIPTION
**Pull request by msfjarvis**
## :loudspeaker: Type of change

- [x] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring

## :scroll: Description
- Updates the `isGitRepo` method to check for things that actually reflect the repository state.
- Makes the "repo is not cloned" Snackbar offer to clone the repository
- Makes `GitOperationActivity` immediately exist when given an unhandled task to perform

## :bulb: Motivation and Context
Fixes #736
Fixes #357
Fixes #490
Fixes #61
Fixes #427

## :green_heart: How did you test it?

Following reproduction steps no longer throw exceptions

- Install a fresh copy of APS
- Select 'Clone from server'
- Select 'Hidden' in the dialog box
- Press back
- Open Settings
- Select 'Edit git server settings' and fill in your server info
- Import your SSH key
- Swipe down to sync the repository

## :pencil: Checklist

- [ ] I ran `./gradlew spotlessApply` before submitting the PR
- [ ] I reviewed submitted code

### CODE REVIEW

File: app/src/main/java/com/zeapo/pwdstore/utils/PasswordRepository.kt [hunk 1]
```diff
@@ -80,7 +80,9 @@ open class PasswordRepository protected constructor() {
         fun isGitRepo(): Boolean {
             if (repository != null) {
                 // Check if remote exists
-                return repository!!.config.getSubsections("remote").isNotEmpty()
+                return repository!!.config.getSubsections("remote").isNotEmpty() &&
+                        repository!!.objectDatabase.exists() &&
+                        repository!!.allRefs.isNotEmpty()
```
Comment (zeapo) [inline app/src/main/java/com/zeapo/pwdstore/utils/PasswordRepository.kt:85]: Aha!! :+1:

File: app/src/main/java/com/zeapo/pwdstore/PasswordFragment.kt [hunk 2]
```diff
@@ -69,8 +70,13 @@ class PasswordFragment : Fragment() {
         swipeRefresher = binding.swipeRefresher
         swipeRefresher.setOnRefreshListener {
             if (!PasswordRepository.isGitRepo()) {
-                Snackbar.make(binding.root, getString(R.string.clone_git_repo), Snackbar.LENGTH_SHORT)
-                    .show()
+                Snackbar.make(binding.root, getString(R.string.clone_git_repo), Snackbar.LENGTH_INDEFINITE)
+                        .setAction(R.string.clone_button) {
+                            val intent = Intent(context, GitServerConfigActivity::class.java)
+                            intent.putExtra(BaseGitActivity.REQUEST_ARG_OP, BaseGitActivity.REQUEST_CLONE)
+                            startActivityForResult(intent, BaseGitActivity.REQUEST_CLONE)
```
Comment (FabianHenneke) [inline app/src/main/java/com/zeapo/pwdstore/PasswordFragment.kt:77]: Is the snackbar dismissed automatically when a new activity is started?

File: app/src/main/java/com/zeapo/pwdstore/utils/PasswordRepository.kt (hunk 1 above)
Comment (FabianHenneke) [reply app/src/main/java/com/zeapo/pwdstore/utils/PasswordRepository.kt:85]: Would it make sense to split this into the parts "isGitRepo" (i.e., we can commit files) and "hasRemote" (i.e., we can sync/push/pull)? I'm not sure how we are currently deciding whether we are able to commit newly created password files or not, but this could maybe be cleaned up in one swoop.

File: app/src/main/java/com/zeapo/pwdstore/PasswordFragment.kt (hunk 2 above)
Comment (msfjarvis) [reply app/src/main/java/com/zeapo/pwdstore/PasswordFragment.kt:77]: Once the action is triggered Snackbar is dismissed.

File: app/src/main/java/com/zeapo/pwdstore/utils/PasswordRepository.kt (hunk 1 above)
Comment (msfjarvis) [reply app/src/main/java/com/zeapo/pwdstore/utils/PasswordRepository.kt:85]: Not at the moment, we forcibly insert the `origin` remote in most code paths.
